#!/usr/bin/env bash

sep="-----------------------------------------------------"

echo "
Aula 01 - noções básicas
$sep
Aula 02 - intro scripts
$sep
Aula 03 - primeiro script
$sep
Aula 04 - variaveis e mini scripts
$sep
Aula 05 - variaveis especiais
$sep
Aula 06 - um script para criar scripts
$sep
Aula 07 - colocando scripts no PATH
$sep
Aula 08 - checando o PID do script
$sep
Aula 09 - um olhada no comando 'test'
$sep
Aula 10 - variáveis indexadas e associativas(arrays)
$sep
"
