#!/usr/bin/env bash
# -----------------------------------------------
# Script   : condicionais
# Descrição: exemplos de testes de expressões condicionais
# Versão   : 1.0
# Autor    : Sergio Donato <sergiodcdn@gmail.com>
# Data     : 29/03/2024
# Licença  : GNU/GPL v3.0
# -----------------------------------------------
# Uso      : ./condicionais ou /caminho/condicionais
# -----------------------------------------------

clear

# Mensagem para o usuário:

echo "O objetivo desse script é comparar o seu número com o número '5'."
read -p "Entre com um número entre 1 a 10: " numero

# Tratar erros:

# =~ indica que a expressão da direita é uma REGEX
# ! negação ou inverso
[[ ! $numero =~ ^[0-9]+$ ]] && echo "Erro! Digite um NÚMERO!" && exit 1

# -le = less or equal
[[ $numero -gt 10 || $numero -le 0 ]] && echo "Erro! O número digitado deve ser entre 1 e 10" && exit 1


# Respostas normais:

# -eq = equal
[[ $numero -eq 5 ]] && echo "Seu número é igual a 5!" && exit 0

# -lt = less than
[[ $numero -lt 5 ]] && echo "Seu número é menor que 5!" && exit 0

# -gt = greater than
[[ $numero -gt 5 ]] && echo "Seu número é maior que 5!" && exit 0
